version: '3.3'

services:
  postgres:
    image: postgres:11.4
    command: postgres -p 1234
    ports:
      - "1234:1234"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=pjwstk"
